language: node_js
node_js:
  - "8"
script:
  - yarn run tsc
  - yarn run lint
  - yarn run coverage
after_success:
  - yarn run coveralls
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
